### PR TITLE
Post page reciever

### PR DESCRIPTION
**Pull request by knargocer**
PostPageReciever

Post Page Reciever :
 * Post Page  Reciever Header component has the picture and the title of the page
*  Post Reciever component illustrates each of the receiving posts
*  Post Page List contains the search and filter functionality and the posts according to the results

This page is very similar to the Post Page Volunteer Page, however, I tried to do the search in a different way. 
I still have some problems with tests, I will try to finish and commit them as well as soon as possible.

### CODE REVIEW

**Comment by orcunsagirsoy** [comment]
Could you make rounded corners for filtering container border (the purple one) to make it look better? You can also use some shadowing for the post card to make the page look more professional. Also, using softer tone of gray for the background color of post cards might make them look more minimalistic. Last also, hover effect on cards might be taken into consideration.

**Review by Ammar-64 — COMMENTED** [review]
Since both receiver and volunteer pages posts are 90% identical, doesn’t it make sense to do them on the same component and change only the props

**Comment by knargocer** [comment]
> Since both receiver and volunteer pages posts are 90% identical, doesn’t it make sense to do them on the same component and change only the props

I think it makes sense, the post list pages and post pages are functioning the same. However, do you mean to merge them in one posts page component and showing all the posts together, or again having two discrete ones but using the same post component and post list component for both?

**Comment by Ammar-64** [comment]
> > Since both receiver and volunteer pages posts are 90% identical, doesn’t it make sense to do them on the same component and change only the props
> 
> I think it makes sense, the post list pages and post pages are functioning the same. However, do you mean to merge them in one posts page component and showing all the posts together, or again having two discrete ones but using the same post component and post list component for both?

Using the same component for both, and not repeat yourself by rewriting the same code twice, so I.can approve and merge the volunteer one, then you can pull it and add ability to function as both and push again, does it make sense?

**Review by betulerkoc — APPROVED** [review]

**Comment by Ammar-64** [comment]
The other one is merged, so pull it fix the conflict and push again

**Review by Ammar-64 — APPROVED** [review]
LGTM

**Pull request merged**
