### PR TITLE
Fix: bug fix for form page

### LINKED ISSUE #47: Donate page bug bash
- add a descriptive text under the logo
- add placeholders to inputs 
- add more options to the donation type 
- add a select one explanation next to the donation type 
- add space between the submit button and the footer

### PR DESCRIPTION
**Pull request by betulerkoc**
Fixes #47 

 - [✓ ] add a descriptive text under the logo  

- [✓] add placeholders to inputs

- [✓ ] add more options to the donation type

- [✓] add a select one explanation next to the donation type

- [✓ ] add space between the submit button and the footer

- [✓ ] add default images

### CODE REVIEW

**Review by Ammar-64 — APPROVED** [review]
LGTM, fix the conflict and you’re good to go

**Comment by Luey-A** [comment]
i have added already added space between the submit button and the footer when i did the button css so i think we may need to fix one of the css files because we will have more space than needed when this is merged.

**Comment by Ammar-64** [comment]
There is a conflict still, can you fix it so I can merge

**Comment by betulerkoc** [comment]
> i have added already added space between the submit button and the footer when i did the button css so i think we may need to fix one of the css files because we will have more space than needed when this is merged.

**Review by orcunsagirsoy — APPROVED** [review]

**Comment by betulerkoc** [comment]
> > i have added already added space between the submit button and the footer when i did the button css so i think we may need to fix one of the css files because we will have more space than needed when this is merged.

Last merge will fix @Luey 👍

**Review by Ammar-64 — APPROVED** [review]
LGTM

**Pull request merged**
