### PR TITLE
Ara translation

### LINKED ISSUE #41: Translation - Ara
translate all the content of the pages to Arabic
check the typos of Ara and Eng

### PR DESCRIPTION
**Pull request by Luey-A**
close #41 
Finished the Arabic translation for the website

### CODE REVIEW

**Review by Ammar-64 — COMMENTED** [review]
LGTM but you have 3 duplicated files

**Comment by Luey-A** [comment]
> duplicated

deleted duplicate files. PTAL

**Review by Ammar-64 — COMMENTED** [review]
There are still 2 duplicated imgs, languageIcon 2 and aboutImg 2

**Comment by Luey-A** [comment]
completed the Arabic translation for the website after merging the other branches

**Review by olaouso — APPROVED** [review]

**Review by Ammar-64 — APPROVED** [review]
LGTM

**Pull request merged**
